database:
  type: sqlite # You can choose only between mysql or sqlite
  host: localhost # Only if type is mysql
  port: 3306 # Only if type is mysql
  database-name: test # Only if type is mysql
  username: root # Only if type is mysql
  password: 123 # Only if type is mysql

options:
  max-backups-number: 9 # max store of backups
  save-task-interval: 1800 # in seconds
  save-on-task: true # Saving player on task (every x seconds)
  save-on-death: true # Saving player on death
  save-on-quit: true # Saving player on quit

messages:
  command-no-permission: '&cYou cannot use that command! No permission &e<niceeqbackups.use>'